# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "cargo"
    directory: "/ffi/gn"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
  - package-ecosystem: "cargo"
    directory: "/ffi/diplomat/c/examples/fixeddecimal_tiny/icu_capi_staticlib_tiny"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
